<#
.SYNOPSIS
    Remediation script to remove specified AppxPackages.

.DESCRIPTION
    This script removes AppxPackages listed in a CSV file (generated by check-appx-to-remove.ps1).
    Intended for use as a remediation script in Configuration Manager Configuration Baselines.

.PARAMETER csvPath
    Path to the CSV file containing the list of Appx package names to remove.

.NOTES
    Author: George Simos <George_Simos@hotmail.com>
    Date: 20-6-2025
    Last Modified: 20-6-2025
    Version: 1.0
#>

# Remediate-Appx-to-Remove.ps1
# Removes AppxPackages listed in a CSV file (from check-appx-to-remove.ps1)
$ErrorActionPreference = 'Stop'
$csvPath = "C:\Path\To\appx-to-remove.csv" # Update this path as needed

if (-not (Test-Path $csvPath)) {
    Write-Output "CSV file not found: $csvPath"
    exit 1
}

$AppxPackagesToRemove = Import-Csv $csvPath | Select-Object -ExpandProperty PackageName
$errors = @()

foreach ($Package in $AppxPackagesToRemove) {
    try {
        # Remove for all users
        Get-AppxPackage -Name $Package -AllUsers | Remove-AppxPackage -AllUsers -ErrorAction SilentlyContinue

        # Remove provisioned package
        Get-AppxProvisionedPackage -Online | Where-Object DisplayName -EQ $Package | Remove-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue
    } catch {
        $errors += "Failed to remove $($Package): $($_)"
    }
}

if ($errors.Count -eq 0) {
    Write-Output "Specified AppxPackages have been removed if present."
    exit 0
} else {
    Write-Output "Some packages could not be removed:`n$($errors -join "`n")"
    exit 1
}